# Generated by Django 4.1.2 on 2022-11-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
